### ISSUE TITLE
Broke webmap

### ISSUE THREAD

**Issue by wabash2** [FreeTAKTeam/FreeTAKHub-Webmap#2]
Webmap was working when logged into FTS UI. My FTS is on a pi4 with access to it on the internet using tailscale and some firewall rules setup using UFW.

Problem timeline is below
1) Webmap loaded fine in the UI however random COT's would appear. I would delete them and they would just reappear.
2) When I connected an atak cliet posted COT's and broadcasted them including driving around to push gps data to the map my clients would still not populate onto the webmap. Deleted the webmap flow and then reinstalled the json file.
3) Installed FTH VideoChecker flow and I am able to stream video from phone to VLC on my computer. However I mustve done something because now I got a "flows stopped due to missing node types" error in node red. "ui_group" and "ui_tab"

![first error](https://user-images.githubusercontent.com/109150421/190552441-f308e4d4-5f49-4b71-9426-89a43cff3741.png)
![second error](https://user-images.githubusercontent.com/109150421/190552455-b41ecdbd-74a2-48cf-a074-8a13578eb1a2.png)

Thanks for any help

**Comment by brothercorvo** [comment]
you have not configured the IP of the webmap. ALso you need to install the dashboard nodes
