### ISSUE TITLE
Non mimified code?

### ISSUE THREAD

**Issue by leshy** [FreeTAKTeam/FreeTAKHub-Webmap#3]
Hi, thanks for the good work!

I'm writing a quick and simple web view in nodejs without side deps, and I was wondering where do you get these icons from? :) Is there a non mimified code for the webmap somewhere that I could look at? does this repo even contain the code I'm interested in? I'm having trouble finding it.

tnx!

**Comment by brothercorvo** [comment]
the webmap uses the component Node-Red  worldmap here
https://github.com/dceejay/RedMap
